"""Added Student and Teacher model

Revision ID: ca2d437c23da
Revises: 2c3475a8d768
Create Date: 2023-03-10 11:45:12.786776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2d437c23da'
down_revision = '2c3475a8d768'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
